site_name: arcadia workspace
site_url: https://netologist.github.io/arcadia/
site_author: Hasan Ozgan

repo_url: https://github.com/netologist/arcadia
repo_name: arcadia workspace
edit_uri: edit/main/docs

nav:
  - Home: "index.md"
  - Installation: "setup/index.md"
  - Tools: "tools/index.md"
  - Project Setup: "project/index.md"

extra_css:
  - assets/css/theme.css

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    logo: material/monitor-cellphone-star
    edit: material/pencil
    view: material/eye
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/weather-sunny
        name: Light Mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: light blue
      toggle:
        icon: material/brightness-auto
        name: Light Mode
  features:
    - navigation.tabs
    - content.action.edit

markdown_extensions:
  - toc:
      permalink: true
      baselevel: 2
  - pymdownx.snippets
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid

docs_dir: docs

plugins:
  - search

strict: true
